# Generated by Django 5.2.6 on 2025-09-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del proveedor')),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Persona de contacto')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
