# Generated by Django 5.2.6 on 2025-09-29 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_product', '0001_initial'),
        ('inventory_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KardexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('input', 'Entrada'), ('output', 'Salida'), ('adjustment', 'Ajuste')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='Referencia como guía, factura o motivo', max_length=255)),
                ('balance', models.IntegerField(help_text='Stock acumulado después de esta entrada/salida')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_stock.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_entries', to='inventory_product.product')),
            ],
            options={
                'verbose_name': 'Movimiento Kardex',
                'verbose_name_plural': 'Movimientos Kardex',
                'ordering': ['-date'],
            },
        ),
    ]
