# Generated by Django 5.2.6 on 2025-09-29 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_product', '0001_initial'),
        ('inventory_stock', '0001_initial'),
        ('suppliers', '0002_remove_supplier_active_supplier_is_active_and_more'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField(verbose_name='Cantidad Recibida')),
                ('reception_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_stock.stocklocation', verbose_name='Ubicación de Almacén')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_product.product', verbose_name='Producto')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Proveedor')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.trip', verbose_name='Viaje Asociado')),
            ],
            options={
                'verbose_name': 'Recepción de Producto',
                'verbose_name_plural': 'Recepciones de Productos',
                'ordering': ['-reception_date'],
            },
        ),
    ]
