# Generated by Django 5.2.6 on 2025-09-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_receiving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreception',
            name='quantity_received',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Recibida'),
        ),
    ]
