# Generated by Django 5.2.6 on 2025-09-21 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_product', '0001_initial'),
        ('inventory_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.PositiveIntegerField(verbose_name='Cantidad mínima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_stock.stocklocation', verbose_name='Ubicación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Alerta de Stock Mínimo',
                'verbose_name_plural': 'Alertas de Stock Mínimo',
                'unique_together': {('product', 'location')},
            },
        ),
    ]
