# Generated by Django 5.2.6 on 2025-09-29 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_product', '0001_initial'),
        ('inventory_stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('volume_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('maintenance', 'Mantenimiento'), ('retired', 'Baja')], default='available', max_length=20)),
                ('odometer_km', models.PositiveIntegerField(default=0)),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='Vence SOAT/Seguro')),
                ('next_maintenance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=30, verbose_name='Licencia')),
                ('license_category', models.CharField(blank=True, max_length=10)),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='Vence Licencia')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('eta_minutes', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_destination', to='inventory_stock.stocklocation')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_origin', to='inventory_stock.stocklocation')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('in_progress', 'En curso'), ('canceled', 'Cancelado')], default='planned', max_length=15)),
                ('odometer_start', models.PositiveIntegerField(blank=True, null=True)),
                ('odometer_end', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_reception', models.BooleanField(default=False, verbose_name='Es recepción')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('planned_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivered_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregado'), ('failed', 'Fallido')], default='pending', max_length=10)),
                ('pod_photo', models.ImageField(blank=True, null=True, upload_to='pod/')),
                ('signature_name', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.trip')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('breakdown', 'Avería'), ('accident', 'Accidente'), ('delay', 'Demora'), ('theft', 'Robo'), ('other', 'Otro')], max_length=12)),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=1)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='incidents/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='transport.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fuel', 'Combustible'), ('toll', 'Peaje'), ('parking', 'Parqueo'), ('other', 'Otro')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='transport.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_product.product', verbose_name='Producto')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='transport.trip', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Producto del Viaje',
                'verbose_name_plural': 'Productos del Viaje',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehiclebrand'),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Modelo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='transport.vehiclebrand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehiclemodel'),
        ),
    ]
