# Generated by Django 5.2.6 on 2025-09-21 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_product', '0001_initial'),
        ('inventory_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad ajustada')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Incremento'), ('decrease', 'Disminución')], max_length=10)),
                ('reason', models.TextField(verbose_name='Motivo del ajuste')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_stock.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_product.product')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
