# Generated by Django 5.2.6 on 2025-09-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('ops_manager', 'Jefe de Operaciones'), ('warehouse_manager', 'Jefe de Almacén'), ('warehouse_staff', 'Operario de Almacén'), ('inventory_controller', 'Control de Inventario'), ('dispatcher', 'Despachador'), ('driver', 'Conductor'), ('viewer', 'Consulta / Solo Lectura')], max_length=20, unique=True, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
